// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4ProjectGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Common\MsSqlConfig.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class MsSqlConfig : Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nnamespace ");
            
            #line 7 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Common\MsSqlConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.CommonNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class MsSqlConfig\r\n    {\r\n        /// <summary>\r\n        /// inse" +
                    "rt into {0} ({1}) values ({2})\r\n        /// </summary>\r\n        public const str" +
                    "ing INSERT_FORMAT = \"INSERT INTO {0} ({1}) VALUES ({2}) \";\r\n\r\n        /// <summa" +
                    "ry>\r\n        /// update {0} set {1} where {2}\r\n        /// </summary>\r\n        p" +
                    "ublic const string UPDATE_FORMAT = \"UPDATE {0} SET {1} WHERE {2} \";\r\n\r\n        /" +
                    "// <summary>\r\n        /// delete from {0} where {1}\r\n        /// </summary>\r\n   " +
                    "     public const string DELETE_FORMAT = \"DELETE FROM {0} WHERE {1} \";\r\n\r\n      " +
                    "  /// <summary>\r\n        /// select count(*) from {0} \r\n        /// </summary>\r\n" +
                    "        public const string SELECT_ALL_COUNT_FORMAT = \"SELECT COUNT(*) FROM {0} " +
                    "\";\r\n\r\n        /// <summary>\r\n        /// select count(*) from {0} where {1} \r\n  " +
                    "      /// </summary>\r\n        public const string SELECT_COUNT_FORMAT = \"SELECT " +
                    "COUNT(*) FROM {0} WHERE {1} \";\r\n\r\n        /// <summary>\r\n        /// select top(" +
                    "{2}) * from {0} where {1}\r\n        /// </summary>\r\n        public const string S" +
                    "ELECT_TOP_FORMAT = \"SELECT TOP({2}) * FROM {0} WHERE {1} \";\r\n\r\n        /// <summ" +
                    "ary>\r\n        /// select top({2}) * from {0} where {1} order by {3}\r\n        ///" +
                    " </summary>\r\n        public const string SELECT_TOP_ORDER_BY_FORMAT = \"SELECT TO" +
                    "P({2}) * FROM {0} WHERE {1} ORDER BY {3} \";\r\n\r\n        /// <summary>\r\n        //" +
                    "/ select * from {0} \r\n        /// </summary>\r\n        public const string SELECT" +
                    "_ALL_FORMAT = \"SELECT * FROM {0} \";\r\n\r\n        /// <summary>\r\n        /// select" +
                    " * from {0} where {1} \r\n        /// </summary>\r\n        public const string SELE" +
                    "CT_FORMAT = \"SELECT * FROM {0} WHERE {1} \";\r\n\r\n        /// <summary>\r\n        //" +
                    "/ select * from {0} where {1} order by {2} \r\n        /// </summary>\r\n        pub" +
                    "lic const string SELECT_ORDER_BY_FORMAT = \"SELECT * FROM {0} WHERE {1} ORDER BY " +
                    "{2} \";\r\n\r\n        /// <summary>\r\n        /// select * from (select row_number() " +
                    "over (order by {2}) as rowindex, * from {0} where {1}) as t where t.rowindex bet" +
                    "ween {3} and {4} \r\n        /// </summary>\r\n        public const string SELECT_PA" +
                    "GE_FORMAT = \"SELECT * FROM (SELECT ROW_NUMBER() OVER (ORDER BY {2}) AS RowIndex," +
                    " * FROM {0} WHERE {1}) AS T WHERE T.RowIndex BETWEEN {3} AND {4} \";\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
