// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4ProjectGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ContextTemplate : Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Data;\r\nusing System.Data.SqlClient;\r\nusing ");
            
            #line 9 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.CommonNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 11 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 13 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("Context : DbProviderFactory\r\n    {\r\n        private Lazy<IDbContextComponent> _Co" +
                    "ntext;\r\n\r\n        protected override IDbContextComponent Context\r\n        {\r\n   " +
                    "         get { return _Context.Value; }\r\n        }\r\n\r\n        public ");
            
            #line 22 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("Context()\r\n            : base()\r\n        {\r\n            _Context = new Lazy<IDbCo" +
                    "ntextComponent>(() => new ");
            
            #line 25 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("ContextWrapper());\r\n");
            
            #line 26 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"

    foreach(DataSchema item in _ColumnList)
    {


            
            #line default
            #line hidden
            this.Write("            _Client");
            
            #line 31 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(" = new Lazy<");
            
            #line 31 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            
            #line 31 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ServiceClassSuffix));
            
            #line default
            #line hidden
            this.Write(">(() => new ");
            
            #line 31 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            
            #line 31 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ServiceClassSuffix));
            
            #line default
            #line hidden
            this.Write("(Context));\r\n");
            
            #line 32 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"

    }

 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 38 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"

    foreach(DataSchema item in _ColumnList)
    {


            
            #line default
            #line hidden
            this.Write("        private Lazy<");
            
            #line 43 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            
            #line 43 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ServiceClassSuffix));
            
            #line default
            #line hidden
            this.Write("> _Client");
            
            #line 43 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n        /// <summary>\r\n        /// ");
            
            #line 45 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableDescription));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        public ");
            
            #line 47 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            
            #line 47 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ServiceClassSuffix));
            
            #line default
            #line hidden
            this.Write(" Client");
            
            #line 47 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return _Client");
            
            #line 49 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(".Value; }\r\n        }\r\n\r\n");
            
            #line 52 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"

    }

 
            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    internal class ");
            
            #line 58 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("ContextWrapper : IDbContextComponent\r\n    {\r\n        public IDbConnection Connect" +
                    "ion { get; set; }\r\n\r\n        public IDbTransaction Transaction { get; set; }\r\n\r\n" +
                    "        public ");
            
            #line 64 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("ContextWrapper()\r\n        {\r\n            this.Connection = new SqlConnection(Conf" +
                    "igManager.GetValue(\"");
            
            #line 66 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextConnectionStringKey));
            
            #line default
            #line hidden
            this.Write(@"""));
            if (this.Connection.State != ConnectionState.Open)
            {
                this.Connection.Open();
            }
        }

        public void Dispose()
        {
            if (this.Transaction != null)
            {
                this.Transaction.Dispose();
                this.Transaction = null;
            }
            if (this.Connection != null)
            {
                this.Connection.Close();
                this.Connection.Dispose();
                this.Connection = null;
            }
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
