// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4ProjectGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ContextTemplate : Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Data;\r\nusing System.Data.SqlClient;\r\nusing ");
            
            #line 9 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.CommonNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 11 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 13 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("ContextWrapper : DbProviderFactory, IDisposable\r\n    {\r\n        #region Context\r\n" +
                    "        internal class ");
            
            #line 16 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("Context : IDbContextComponent\r\n        {\r\n            public IDbConnection Connec" +
                    "tion { get; private set; }\r\n\r\n            public IDbTransaction Transaction { ge" +
                    "t; set; }\r\n\r\n            public ");
            
            #line 22 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write(@"Context(string connectionString)
            {
                this.Connection = new SqlConnection(connectionString);
                if (this.Connection.State != ConnectionState.Open)
                {
                    this.Connection.Open();
                }
            }
        }

        protected override IDbContextComponent Context { get; set; }
        private bool _Disposed = false;

        public ");
            
            #line 35 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("ContextWrapper()\r\n        {\r\n            string connectionString = ConfigManager." +
                    "GetValue(\"");
            
            #line 37 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextConnectionStringKey));
            
            #line default
            #line hidden
            this.Write("\");\r\n            Context = new ");
            
            #line 38 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ContextClassPrefix));
            
            #line default
            #line hidden
            this.Write("Context(connectionString);\r\n        }\r\n\r\n        protected virtual void Dispose(b" +
                    "ool disposing)\r\n        {\r\n            if (!this._Disposed)\r\n            {\r\n");
            
            #line 45 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"

    foreach(DataSchema item in _ColumnList)
    {


            
            #line default
            #line hidden
            this.Write("                if (this._Client");
            
            #line 50 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n                {\r\n                    this._Client");
            
            #line 52 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n                }\r\n");
            
            #line 54 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"

    }

 
            
            #line default
            #line hidden
            this.Write(@"                if (disposing)
                {
                    if (IsBeginTrans)
                    {
                        Rollback();
                    }
                    if (Context.Transaction != null)
                    {
                        Context.Transaction.Dispose();
                        Context.Transaction = null;
                    }
                    if (Context.Connection != null)
                    {
                        Context.Connection.Close();
                        Context.Connection.Dispose();
                    }
                }
            }
            this._Disposed = true;
        }

        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }
        #endregion

        #region Client属性
");
            
            #line 87 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"

    foreach(DataSchema item in _ColumnList)
    {


            
            #line default
            #line hidden
            this.Write("        private ");
            
            #line 92 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            
            #line 92 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ServiceClassSuffix));
            
            #line default
            #line hidden
            this.Write(" _Client");
            
            #line 92 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n        /// <summary>\r\n        /// ");
            
            #line 94 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableDescription));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        public ");
            
            #line 96 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            
            #line 96 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ServiceClassSuffix));
            
            #line default
            #line hidden
            this.Write(" Client");
            
            #line 96 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get\r\n            {\r\n                if (this._Client");
            
            #line 100 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n                {\r\n                    this._Client");
            
            #line 102 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 102 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            
            #line 102 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ServiceClassSuffix));
            
            #line default
            #line hidden
            this.Write("(this.Context);\r\n                }\r\n                return _Client");
            
            #line 104 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n        }\r\n\r\n");
            
            #line 108 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\BLL\ContextTemplate.tt"

    }

 
            
            #line default
            #line hidden
            this.Write("        #endregion\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
