// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4ProjectGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ManagerTemplate : Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated>\r\n// 自动生成请勿修改\r\n// </auto-generated>\r\n\r\nusing ");
            
            #line 10 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.CommonNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 12 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ManagerNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// ");
            
            #line 15 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_ColumnList.FirstOrDefault().TableDescription));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public partial class ");
            
            #line 17 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            
            #line 17 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ManagerClassSuffix));
            
            #line default
            #line hidden
            this.Write(" : MsSqlAccessBase\r\n    {\r\n        public ");
            
            #line 19 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            
            #line 19 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ManagerClassSuffix));
            
            #line default
            #line hidden
            this.Write("(IDbContextComponent context)\r\n            : base(context)\r\n        { }\r\n\r\n      " +
                    "  protected override string TableName\r\n        {\r\n            get { return \"");
            
            #line 25 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write("\"; }\r\n        }\r\n\r\n        protected override string InsertString\r\n        {\r\n   " +
                    "         get\r\n            {\r\n                return string.Format(MsSqlConfig.IN" +
                    "SERT_FORMAT,\r\n                    this.TableName,\r\n                    \"");
            
            #line 34 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetInsertField(_ColumnList)));
            
            #line default
            #line hidden
            this.Write("\",\r\n                    \"");
            
            #line 35 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetInsertValue(_ColumnList)));
            
            #line default
            #line hidden
            this.Write("\"\r\n                );\r\n            }\r\n        }\r\n\r\n        protected override str" +
                    "ing UpdateString\r\n        {\r\n            get\r\n            {\r\n");
            
            #line 44 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"

    if(DataManager.IsUpdate(_ColumnList))
    {
 
            
            #line default
            #line hidden
            this.Write("                return string.Format(MsSqlConfig.UPDATE_FORMAT,\r\n                " +
                    "    this.TableName,\r\n                    \"");
            
            #line 50 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetUpdateField(_ColumnList, false)));
            
            #line default
            #line hidden
            this.Write("\",\r\n                    \"");
            
            #line 51 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetUpdateField(_ColumnList, true)));
            
            #line default
            #line hidden
            this.Write("\"\r\n                );\r\n");
            
            #line 53 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"

    } else{

            
            #line default
            #line hidden
            this.Write("                throw new System.NotImplementedException();\r\n");
            
            #line 57 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\DAL\ManagerTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
