// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4ProjectGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ModelTemplate : Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated>\r\n// 自动生成请勿修改\r\n// </auto-generated>\r\n\r\nnamespace ");
            
            #line 10 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ModelNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// ");
            
            #line 13 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_ColumnList.FirstOrDefault().TableDescription));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public partial class ");
            
            #line 15 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            
            #line 15 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ModelClassSuffix));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 17 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"

    foreach(DataSchema item in _ColumnList)
    {


            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// ");
            
            #line 23 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Description));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        public virtual ");
            
            #line 25 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.CSharpDataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 25 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ColumnName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 26 "E:\zy\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"

    }

 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
