// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4ProjectGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ModelTemplate : Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated>\r\n// 自动生成请勿修改\r\n// </auto-generated>\r\nusing System;\r\nusing ");
            
            #line 10 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.CommonNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 12 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ModelNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// ");
            
            #line 15 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_ColumnList.FirstOrDefault().TableDescription));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public partial class ");
            
            #line 17 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            
            #line 17 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.ModelClassSuffix));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 19 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"

    foreach(DataSchema item in _ColumnList)
    {


            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// ");
            
            #line 25 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Description));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        public virtual ");
            
            #line 27 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.CSharpDataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 27 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ColumnName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 28 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"

    }

 
            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    public class ");
            
            #line 34 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write("Config : ISqlConfig\r\n    {\r\n        #region SQL语句\r\n        private Lazy<string> _" +
                    "TableName = new Lazy<string>(() =>\r\n        {\r\n            return \"");
            
            #line 39 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write("\";\r\n        });\r\n\r\n        private Lazy<string> _Insert = new Lazy<string>(() =>\r" +
                    "\n        {\r\n            return \"insert into ");
            
            #line 44 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" (");
            
            #line 44 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetInsertField(_ColumnList)));
            
            #line default
            #line hidden
            this.Write(") values (");
            
            #line 44 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetInsertValue(_ColumnList)));
            
            #line default
            #line hidden
            this.Write(") \";\r\n        });\r\n\r\n        private Lazy<string> _InsertIdentity = new Lazy<stri" +
                    "ng>(() =>\r\n        {\r\n            return \"insert into ");
            
            #line 49 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" (");
            
            #line 49 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetInsertField(_ColumnList)));
            
            #line default
            #line hidden
            this.Write(") values (");
            
            #line 49 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetInsertValue(_ColumnList)));
            
            #line default
            #line hidden
            this.Write("); select scope_identity() \";\r\n        });\r\n\r\n        private Lazy<string> _Updat" +
                    "e = new Lazy<string>(() =>\r\n        {\r\n");
            
            #line 54 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"

    if(DataManager.IsUpdate(_ColumnList))
    {
 
            
            #line default
            #line hidden
            this.Write("            return \"update ");
            
            #line 58 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" set ");
            
            #line 58 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetUpdateField(_ColumnList, false)));
            
            #line default
            #line hidden
            this.Write(" where ");
            
            #line 58 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataManager.GetUpdateField(_ColumnList, true)));
            
            #line default
            #line hidden
            this.Write(" \";\r\n");
            
            #line 59 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"

    } else{

            
            #line default
            #line hidden
            this.Write("                throw new System.NotImplementedException();\r\n");
            
            #line 63 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n\r\n        private Lazy<string> _Delete = new Lazy<string>(() =>\r\n   " +
                    "     {\r\n            return \"delete from ");
            
            #line 70 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" where {0} \";\r\n        });\r\n\r\n        private Lazy<string> _SelectAllCount = new " +
                    "Lazy<string>(() =>\r\n        {\r\n            return \"select count(*) from ");
            
            #line 75 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" \";\r\n        });\r\n\r\n        private Lazy<string> _SelectCount = new Lazy<string>(" +
                    "() =>\r\n        {\r\n            return \"select count(*) from ");
            
            #line 80 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" where {0} \";\r\n        });\r\n\r\n        private Lazy<string> _SelectTop = new Lazy<" +
                    "string>(() =>\r\n        {\r\n            return \"select top({0}) * from ");
            
            #line 85 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" where {1} \";\r\n        });\r\n\r\n        private Lazy<string> _SelectTopOrder = new " +
                    "Lazy<string>(() =>\r\n        {\r\n            return \"select top({0}) * from ");
            
            #line 90 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" where {1} order by {2} \";\r\n        });\r\n\r\n        private Lazy<string> _SelectAl" +
                    "l = new Lazy<string>(() =>\r\n        {\r\n            return \"select * from ");
            
            #line 95 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" \";\r\n        });\r\n\r\n        private Lazy<string> _SelectWhere = new Lazy<string>(" +
                    "() =>\r\n        {\r\n            return \"select * from ");
            
            #line 100 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" where {0} \";\r\n        });\r\n\r\n        private Lazy<string> _SelectWhereOrder = ne" +
                    "w Lazy<string>(() =>\r\n        {\r\n            return \"select * from ");
            
            #line 105 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(" where {0} order by {1} \";\r\n        });\r\n\r\n        private Lazy<string> _SelectPa" +
                    "ge = new Lazy<string>(() =>\r\n        {\r\n            return \"select * from (selec" +
                    "t row_number() over (order by {1}) as RowIndex, * from ");
            
            #line 110 "E:\zy\T4\T4\T4ProjectGenerator\T4ProjectGenerator\Template\Model\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_TableName));
            
            #line default
            #line hidden
            this.Write(@" where {0}) as t where t.RowIndex between {2} and {3} "";
        });
        #endregion

        public string TableName
        {
            get { return _TableName.Value; }
        }

        public string Insert
        {
            get { return _Insert.Value; }
        }

        public string InsertIdentity
        {
            get { return _InsertIdentity.Value; }
        }

        public string Update
        {
            get { return _Update.Value; }
        }

        public string Delete
        {
            get { return _Delete.Value; }
        }

        public string SelectAllCount
        {
            get { return _SelectAllCount.Value; }
        }

        public string SelectCount
        {
            get { return _SelectCount.Value; }
        }

        public string SelectTop
        {
            get { return _SelectTop.Value; }
        }

        public string SelectTopOrder
        {
            get { return _SelectTopOrder.Value; }
        }

        public string SelectAll
        {
            get { return _SelectAll.Value; }
        }

        public string SelectWhere
        {
            get { return _SelectWhere.Value; }
        }

        public string SelectWhereOrder
        {
            get { return _SelectWhereOrder.Value; }
        }

        public string SelectPage
        {
            get { return _SelectPage.Value; }
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
